name: "CodeQL"

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 23 * * 3' # run the workflow at 23:00 Wednesday

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: "cpp"

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3