name: Build Solution

on:
  pull_request:
    branches: [ "master" ]

env:
  BUILD_CONFIGURATION: Release
  PLATFORM: x64
  UPLOAD_PATH: D:/a/CwAPI3D.Net.Bridge/CwAPI3D.Net.Bridge/examplelib/bin/Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
            
        with:
          msbuild-architecture: 'x64'

      - name: BUILD SOLUTION
        run: |
          msbuild cwpai3d_bridge.sln /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.PLATFORM }} 

      # - name: Test
      #  run: dotnet test ./CWAPI3D_UnitTest/CWAPI3D_UnitTest.csproj --no-restore --verbosity normal

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CwAPI3D.Net.Bridge
          path: ${{ env.UPLOAD_PATH }}
