name: Cppcheck

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install cppcheck
      run: |
        choco install cppcheck -y

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --error-exitcode=1 .