name: Release to NuGet

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Push events to matching v1.0.0 tags
  pull_request:
    branches:
        - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 
  PACKAGE_PROJECT_FILE_PATH: './CwAPI3D.Net.Bridge.sln' 
  NUSPEC_FILE_PATH: './.nuspec'
  BUILD_CONFIGURATION: Release
  PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2 
        with:
          msbuild-architecture: 'x64'

      - name: Build
        run: |
          msbuild ${{env.PACKAGE_PROJECT_FILE_PATH}} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.PLATFORM }} 

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0
        with:
          nuget-version: 'latest'

      - name: Pack
        run: nuget pack ${{ env.NUSPEC_FILE_PATH }} -OutputDirectory out -Verbosity detailed

      - name: Push
        run: nuget push ./out/*.nupkg -ApiKey ${{ env.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json